export const data = [
  {
    id: 10,
    title: "PLAN BÁSICO",
    description:
      "Donde le facilitamos el logo, paleta de colores y el set básico para poder usar la marca Face It.",
    img: "/Basico.svg",
    servicios: [
      "Logo.",
      "Paleta de Colores.",
      "Creación de instagram.",
      "Creación de Gmail.",
      "Creación de TikTok.",
      "Creación de Twitter.",
      "Formulario.",
    ],
  },
  {
    id: 20,
    title: "PLAN PROFESIONAL",
    description:
      "Una asesoría donde explicamos el método que usamos para organizar los eventos, incluyendo el tono que usamos en los mensajes, etc… En el caso que quiera iniciar este tipo de eventos con una marca propia que no sea Face It!",
    img: "/Profesional.svg",
    servicios: [
      "Mensajes a bares.",
      "Mensajes directos.",
      "Mensajes Whatsapp.",
      "Organización del evento.",
      "Tono de mensajes.",
      "Formulario de eventos.",
      "Animación del evento.",
      "Correo invitación al evento.",
    ],
    verMas: [
      "Correo de recepción de formulario.",
      "Recomendaciones de carta-bar.",
      "Elección de perfiles y detección de alertas.",
      "Control de ingresos y egresos.",
      "Incluye 2 horas de videollamada.",
    ],
    button: "VER MÁS",
  },
  {
    id: 30,
    title: "PLAN PREMIUM",
    description:
      "La propuesta que combina las 2 anteriores, que incluye además de la marca, todos los contenidos que fuimos publicando para que tenga material para adaptarlo a su país (si hace falta) para que sólo tenga que programar el contenido en las redes sociales.",
    img: "/Premium.svg",
    servicios: [
      "Logo.",
      "Paleta de Colores.",
      "Creación de instagram.",
      "Creación de Gmail.",
      "Formulario y Data.",
      "Creación de TikTok.",
      "Creación de Twitter.",
      "Posteos a Canva y videos.",
    ],
    verMas: [
      "Email marketing (chimp).",
      "Asesoria.",
      "Mensaje a bares.",
      "Mensajes directos.",
      "Mensajes Whatsapp.",
      "Correo invitación al evento.",
      "Correo de recepción de formulario.",
      "Organización del eventos.",
      "Tono de Mensajes.",
      "Formulario de eventos.",
      "Recomendaciones de carta-bar.",
      "Animación del evento.",
      "Elección de perfiles y detección de alertas.",
      "Control de ingresos y egresos.",
      "3 horas de videollamada.",
    ],
    button: "VER MÁS",
  },
];
