export const data = [
  {
    id: 1,
    title: "Plan básico",
    description: "Logo, paleta de colores y set básico.",
    acordeon: "Incluye:",
    servicios: [
      "Logo.",
      "Paleta de Colores.",
      "Creación de instagram.",
      "Creación de Gmail.",
      "Creación de TikTok.",
      "Creación de Twitter.",
      "Formulario.",
    ],
  },
  {
    id: 2,
    title: "Plan profesional",
    description: "Asesoría en organización de eventos.",
    acordeon: "Incluye:",
    servicios: [
      "Mensajes a bares.",
      "Mensajes directos.",
      "Mensajes Whatsapp.",
      "Correo invitación al evento.",
      "Correo de recepción de formulario.",
      "Organización del evento.",
      "Tono de mensajes.",
      "Formulario de eventos.",
      "Recomendaciones de carta-bar.",
      "Animación del evento.",
      "Elección de perfiles y detección de alertas.",
      "Control de ingresos y egresos.",
      "Incluye 2 horas de videollamada.",
    ],
  },
  {
    id: 3,
    title: "Plan premium",
    description: "Set básico y asesorías.",
    acordeon: "Incluye:",
    servicios: [
      "Logo.",
      "Paleta de Colores.",
      "Creación de instagram.",
      "Creación de Gmail.",
      "Formulario y Data.",
      "Creación de TikTok.",
      "Creación de Twitter.",
      "Posteos a Canva y videos.",
      "Email marketing (chimp).",
      "Asesoria.",
      "Mensaje a bares.",
      "Mensajes directos.",
      "Mensajes Whatsapp.",
      "Correo invitación al evento.",
      "Correo de recepción de formulario.",
      "Organización del eventos.",
      "Tono de Mensajes.",
      "Formulario de eventos.",
      "Recomendaciones de carta-bar.",
      "Animación del evento.",
      "Elección de perfiles y detección de alertas.",
      "Control de ingresos y egresos.",
      "3 horas de videollamada.",
    ],
  },
];
